apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogging-platform-ingress
  namespace: blogging-platform
  labels:
    app.kubernetes.io/part-of: blogging-platform
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - writersroom.developersubodh.in
        - api.writersroom.developersubodh.in
      secretName: blogging-platform-tls
  rules:
    - host: writersroom.developersubodh.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blogging-frontend-svc
                port:
                  number: 8080
    - host: api.writersroom.developersubodh.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blogging-backend-svc
                port:
                  number: 3000
