apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blogging-platform-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: blogging-platform
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blogging-platform

  source:
    repoURL: https://github.com/SSM2011/blogging-platform-fullstack.git
    targetRevision: staging
    path: infrastructure/kubernetes/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: blogging-platform

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
