apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blogging-platform
resources:
- ../../base
- patches/pdb.yaml
commonLabels:
  environment: production
patches:
- path: patches/frontend-replicas.yaml
- path: patches/backend-replicas.yaml
- path: patches/hpa.yaml
images:
- name: blogging-platform/backend
  newName: 340577260063.dkr.ecr.ap-south-1.amazonaws.com/blogging-platform/backend
  newTag: build-7-20699f8
- name: blogging-platform/frontend
  newName: 340577260063.dkr.ecr.ap-south-1.amazonaws.com/blogging-platform/frontend
  newTag: build-7-20699f8
