apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blogging-platform

resources:
- ../../base
- patches/pdb.yaml

namePrefix: prod-

commonLabels:
  environment: production

patches:
- path: patches/frontend-replicas.yaml
- path: patches/backend-replicas.yaml
- path: patches/hpa.yaml

images:
- name: blogging-platform/backend
  newName: 139822119368.dkr.ecr.ap-south-1.amazonaws.com/blogging-platform/backend
  newTag: build-23-c169250
- name: blogging-platform/frontend
  newName: 139822119368.dkr.ecr.ap-south-1.amazonaws.com/blogging-platform/frontend
  newTag: build-23-c169250

configMapGenerator:
- behavior: merge
  literals:
  - NODE_ENV=production
  - PORT=3000
  - AWS_REGION=ap-south-1
  - AWS_BUCKET_NAME=my-fullstack-blogging-platform
  name: backend-config
